### ISSUE TITLE
MRPT library missing master branch for ROS Hydro

### ISSUE THREAD

**Issue by avidken** [mrpt-ros-pkg/mrpt_slam#1]
Dear Jose-Luis,

My name is Kenneth and I work for a start-up company called Avidbots, www.avidbots.com.  I am responsible for integrating SLAM algorithms into our indoor cleaning robots.  

One of our founders used your library in his previous work, and liked it very much.  He suggested I use this library for our work.

I was trying to obtain the MRPT ROS package via the ROS Hydro Github link at http://wiki.ros.org/mrpt_icp_slam_2d, but I couldn't find the master branch anymore.

Would you be able to help us by providing us the most recent working version that worked with ROS Hydro?

We are happy to contribute to your project as part of our development!

Hope to hear from you soon!

Sincerely,
Kenneth Lee
kenneth@avidbots.com

**Comment by jlblancoc** [comment]
Dear Kenneth, 

Thanks for your interest and possitive feedback on MRPT. 
 
Unfortunately, maintaining mrpt ROS wrappers is low priority in our research group (as it is obvious from the huge gap between mrpt functionalities and what is actually exposed to ROS!) so we normally work on that in "spare time"...

From the 4 ROS repos in https://github.com/mrpt-ros-pkg, `mrpt_slam` is the only one that is actually empty. 

To put it clear: there has never been a working version of the modules in `mrpt_slam`. Their names are there just as a "declaration of intentions". icp-slam-2d would be probably the most interesting node in that pkg, that is why the first work on it was precisely the wiki documentation you linked. So: yes, the docs were written BEFORE the code to serve as a design guide, as opposed to the usual order ;-) 

I could provide any guidance you may need if you want to work on implementing that node, which would be a fantastic contribution to both the ROS & MRPT communities ;-)

Some starting points (that you probably already know): 
  - standalone app icp-slam code: https://github.com/jlblancoc/mrpt/blob/master/apps/icp-slam/icp-slam_main.cpp
  - As an example of ROS node skeleton: https://github.com/mrpt-ros-pkg/mrpt_navigation/tree/indigo-devel/mrpt_local_obstacles

Cheers, 
JL
