### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by Logrus** [mrpt-ros-pkg/mrpt_slam#12]
Hi @jlblancoc,

I would like to brush up the code a bit, Should it conform to [MRPT Style Guide ](https://github.com/MRPT/mrpt/blob/master/doc/MRPT_Coding_Style.md) or to [ROS C++ Style Guide](http://wiki.ros.org/CppStyleGuide). I want to get rid of the mixing of the white spaces.
Is there a general guideline for ``mrpt-ros-pkg``?

Thanks!

**Comment by jlblancoc** [comment]
Hi @Logrus ! 

Well... this is ROS, so... let's go the ROS way :-) 
Thanks for the offering. I've just added you to the team of developers of this Org (yeah!), so you can more easily contribute without the need to do PR. 

Feel free to add a small note to this repo README (and to `mrpt_navigation` as well) explaining the recommended format from now on.

**Comment by Logrus** [comment]
Thank you! That's nice :)
