### ISSUE TITLE
mrpt_ekf_slam_2d node still playing the rawlog file when the path of the rawlog file is not provided

### ISSUE THREAD

**Issue by andrestoga** [mrpt-ros-pkg/mrpt_slam#14]
Hi,

I don't know if it is a bug or not but the node still keep playing the rawlog file even though I'm not specifying the path of the rawlog file.

[ WARN] [1478060837.964899981]: PLAY FROM RAWLOG FILE: /home/andrestoga/ros_Map_Merging/src/mrpt_navigation/mrpt_ekf_slam_2d/tutorial/kf-slam_demo_2d.rawlog

By the way, what does that mean "Online Regime"?

Best,

**Comment by Logrus** [comment]
Hi @andrestoga,

SLAM nodes can work in two modes: offline and online. 

**Offline mode with rawlog:**
If you specify rawlog file in lunch file, line in  ekf_slam_2d_rawlog.launch then the node will read the whole rawlog file into the memory. Then it processes it consequently.
In ekf_slam_2d_rawlog.launch this line specifies it:
```
<param name="rawlog_filename" value="$(find mrpt_ekf_slam_2d)/tutorial/kf-slam_demo_2d.rawlog"/>
```
If the file is missing, the node switches to online mode.

**Online mode (regime):**
In online mode, ekf_slam_2d_node reads messages from topics as you would expect.
When it sees messages in /laser_scans, /landmarks, /beacons (depending on the SLAM) it processes them.
However in demo ekf_slam_2d.launch file the line:
```
<!--PLAY RAWLOG FILE-->
<include file="$(find mrpt_rawlog)/launch/demo_play_ekf_2d.launch" />
```
launches mrpt_rawlog_node to read (convert) and publish messages from rawlog file. The ekf_slam_2d_node now doesn't read the rawlog file, but only listens to the  topics.

Hope this helps.

Best,
Vlad

**Comment by andrestoga** [comment]
Hi @Logrus,

Thanks for the explanation!
