### ISSUE TITLE
Porting ROS wrapper packages to MRPT-2.0

### ISSUE THREAD

**Issue by bergercookie** [mrpt-ros-pkg/mrpt_slam#24]
Hey @mrpt-ros-pkg/team-mrpt_navigation,

As Jose [announced today](https://groups.google.com/forum/#!topic/mrpt-users/550W-0EHRNE) MRPT-1.5 is now stable. That means that we should be moving towards supporting 2.0 as well.

The standard way to do that would be to:
- Initialize a mrpt-1.5 (stable) branch which would track the corresponding mrpt-1.5 branch of [MRPT/mrpt](https://github.com/MRPT/mrpt/tree/mrpt-1.5)
- Make new travis.yml files for mrpt_slam, mrpt_navigation repos and have them compile cleanly with MRPT-2.0. As this [SO post suggests](https://stackoverflow.com/a/37544452/2843583) we can have a different travis file for each one of the branches, to make sure that both the stable and the devel branch build cleanly.

P.S: As of now I am making 2 (hopefully final) pull requests to mrpt_navigation, mrpt_slam and after that I'll start working on porting the rest of the code to 2.0.

Cheers,
Nikos

**Comment by jlblancoc** [comment]
Thanks for pushing so hard! 👍 

I realized that a multi-version travis script was already done for mrpt_navigation [here](https://github.com/mrpt-ros-pkg/mrpt_navigation/blob/master/.travis.yml#L13), but wasn't imported here (!!). Do it if you want to, for now, using the same PPA repo for both MRPT 1.5 and 2.0. I'll soon create separate PPAs for the different versions, so it'll be just a matter of changing an URL ;-)

**Comment by jlblancoc** [comment]
Closing: branches compatibility with MRPT versions is explained in the [README](https://github.com/mrpt-ros-pkg/mrpt_slam/blob/master/README.md), and travis supports docker for building against different MRPT, ROS and Ubuntu versions. 👍
