### ISSUE TITLE
rbpf_slam landmarks with unknown id 

### ISSUE THREAD

**Issue by Magnusgaertner** [mrpt-ros-pkg/mrpt_slam#33]
how would one modify the ini file to use ObservationRangeBearing observations to build a landmark based map?

**Comment by jlblancoc** [comment]
Just using id=-1 should work... Let us know if there's some problem in the ros wrapper of that mrpt functionality.

See: http://docs.ros.org/jade/api/mrpt_msgs/html/msg/SingleRangeBearingObservation.html

**Comment by jlblancoc** [comment]
Yes, using id=-1 should invoke the data association method for EKF 2D or 3D. Let us know your results / issues!

Cheers.

**Comment by olliejday** [comment]
Hi, 

Yeah I ran id=-1 for EKF 2D and it worked really well!! 

Thanks :)
