### ISSUE TITLE
Error compiling on ROS

### ISSUE THREAD

**Issue by dikokob** [mrpt-ros-pkg/mrpt_slam#38]
`>> catkin_make`

`>> [ 82%] Built target mrpt_localization_node
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`

**Comment by Logrus** [comment]
This is related to [mrpt_navigation](https://github.com/mrpt-ros-pkg/mrpt_navigation) repo and the issue should be created there.
