### ISSUE TITLE
Can't find graphslam_2d nodes

### ISSUE THREAD

**Issue by AdriJS** [mrpt-ros-pkg/mrpt_slam#39]
I installed both mrpt_slam and mrpt_graphslam_2d, but when I run "rosrun mrpt_graphslam_2d <tab_completion>" ROS is not able to find any node inside this package. Inside this package there are only 2 things: a folder called cmake and the file package.xml, is this correct?

```
adri@hpENVY173D:~$ sudo apt-get install ros-kinetic-mrpt-slam 
[sudo] password di adri: 
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
ros-kinetic-mrpt-slam is already the newest version (0.1.5-0xenial-20180125-163526-0800).
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
```

```
adri@hpENVY173D:~$ sudo apt-get install ros-kinetic-mrpt-graphslam-2d 
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
ros-kinetic-mrpt-graphslam-2d is already the newest version (0.1.5-0xenial-20180125-151944-0800).
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
```

`adri@hpENVY173D:~$ roscd mrpt_graphslam_2d/`

```
adri@hpENVY173D:/opt/ros/kinetic/share/mrpt_graphslam_2d$ ls
cmake  package.xml

```

I tried to install by downloading the source code from GitHub but also in this case it was impossible to find any executable.

Finally I tried to install everything from the official repositories find on this [page](https://www.mrpt.org/MRPT_in_GNU/Linux_repositories)
but nothing changed: same issues.

```
adri@hpENVY173D:~$ sudo apt-get install mrpt-apps libmrpt-dev
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
libmrpt-dev is already the newest version (1:1.3.2-1).
mrpt-apps is already the newest version (1:1.3.2-1).
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
```

Can someone help me to use this package and to find a solution? Have I missed something?

Thank you.
AdriJS

**Comment by jlblancoc** [comment]
Hi, the graph Slam pkgs require the latest version of mrpt so they must be
built from sources...
