### ISSUE TITLE
TO-DO: cannot release to ROS melodic

### ISSUE THREAD

**Issue by jlblancoc** [mrpt-ros-pkg/mrpt_slam#45]
Due a missing dep: multimaster_msgs_fkie

To do: either,
- Remove the dependency
- Contribute a release to melodic of that pkg.

**Comment by bergercookie** [comment]
> Due a missing dep: multimaster_msgs_fkie

Hmm, that dependency is heavily used in the multi-robot part of mrpt_graphslam_2d. I'm not that familiar with the work it needs to release an existing package for a new ROS version but I can definitely take a look at it...

**Comment by jlblancoc** [comment]
Thanks! Just opened 
https://github.com/fkie/multimaster_fkie/issues/76

**Comment by jlblancoc** [comment]
Done! rosdistro PR [here](https://github.com/ros/rosdistro/pull/18655)
