### ISSUE TITLE
New Melodic release

### ISSUE THREAD

**Issue by clalancette** [mrpt-ros-pkg/mrpt_slam#48]
After #46, I think mrpt has a good chance of building on the ROS buildfarm for Melodic (i.e. http://build.ros.org/view/Mbin_uB64/job/Mbin_uB64__mrpt_graphslam_2d__ubuntu_bionic_amd64__binary/ should be fixed).  Could we have another release of mrpt_slam to make those jobs succeed?  Thanks!

**Comment by jlblancoc** [comment]
Done! https://github.com/ros/rosdistro/pull/19155
Let's see...
