### ISSUE TITLE
error CMAKE

### ISSUE THREAD

**Issue by Adlirrahaman** [mrpt-ros-pkg/mrpt_slam#49]
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "mrpt_bridge" with
  any of the following names:

    mrpt_bridgeConfig.cmake
    mrpt_bridge-config.cmake

  Add the installation prefix of "mrpt_bridge" to CMAKE_PREFIX_PATH or set
  "mrpt_bridge_DIR" to a directory containing one of the above files.  If
  "mrpt_bridge" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  turtlebot3/turtlebot3_slam-master/mrpt_ekf_slam_2d/CMakeLists.txt:8 (find_package)

-- Could not find the required component 'mrpt_bridge'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "mrpt_bridge" with
  any of the following names:

    mrpt_bridgeConfig.cmake
    mrpt_bridge-config.cmake

  Add the installation prefix of "mrpt_bridge" to CMAKE_PREFIX_PATH or set
  "mrpt_bridge_DIR" to a directory containing one of the above files.  If
  "mrpt_bridge" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  turtlebot3/turtlebot3_slam-master/mrpt_ekf_slam_2d/CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/adlir/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/adlir/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

the package cant build or cmake

**Comment by Adlirrahaman** [comment]
are this package compatible on turtlebot burger ?

**Comment by Logrus** [comment]
@Adlirrahaman, I don't know to be honest, I haven't worked with turtlebot burger. You can of course just check it out if it works out of the box and if not, feel free to introduce changes to make it work.

**Comment by Adlirrahaman** [comment]
When I tried to catkin_make there was an error like :

-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
The CMAKE_CXX_COMPILER:

/usr/bin/c++

is not a full path to an existing compiler tool.

Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!

whats the trouble is it?

**Comment by Logrus** [comment]
It seems that you either don't have gcc installed or your environment isn't set up correctly.
Please check that the following commands give you something:
```which c++```
and ```which gcc```.
If they give you an empty prompt, probably you'd need to run:
```
apt-get update
apt-get install -y g++-7
```


Here is the page where you can find how to install GCC the C compiler on Ubuntu 18.04 Bionic Beaver Linux. In principle it should also work for other ubuntu distros.
https://linuxconfig.org/how-to-install-gcc-the-c-compiler-on-ubuntu-18-04-bionic-beaver-linux 

Also try to clean your catkin environment and rebuild.
Run
```
catkin_make clean && catkin_make
```

**Comment by Logrus** [comment]
Closing since this also was tackled here: https://github.com/MRPT/mrpt/issues/880
