### ISSUE TITLE
How to produce landmarks topic?

### ISSUE THREAD

**Issue by tiberium24** [mrpt-ros-pkg/mrpt_slam#50]
Do you use the PCL library to produce the landmarks when you have a lidar? Are there any packages readily available to use?

**Comment by brolin-botsync** [comment]
@tiberium24 We you able to get the landmark topic working. I am planning to use a separate node and publish the lidar scan that I already have in the mrpt_msgs/ObservationRangeBearing type. But I am just confused as to how I can give the id for the different landmarks that I detect after I have moved the robot.
