### ISSUE TITLE
How to cmake mrpt_slam package 

### ISSUE THREAD

**Issue by Adlirrahaman** [mrpt-ros-pkg/mrpt_slam#51]
I've tried to build mrpt slam package then I've got trouble :

You should either add add_message_files() and/or add_service_files() calls
  or remove the invocation of generate_messages().
Call Stack (most recent call first):
  /opt/ros/kinetic/share/genmsg/cmake/genmsg-extras.cmake:307 (include)
  turtlebot3/turtlebot3_ekf-master/CMakeLists.txt:70 (generate_messages)

-- fastslam: 0 messages, 0 services
-- +++ processing catkin package: 'mrpt_sensorlib'
-- ==> add_subdirectory(turtlebot3/turtlebot3_ekf-slam/mrpt_sensors-master/mrpt_sensorlib)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
**CMake Error** at /usr/share/mrpt/MRPTConfig.cmake:2 (MESSAGE):
  find_package(MRPT ...  module_name) is **deprecated**.Replace by:
  find_package(mrpt-module_name)Please, read:
  https://docs.mrpt.org/reference/devel/mrpt_from_cmake.html
Call Stack (most recent call first):
  turtlebot3/turtlebot3_ekf-slam/mrpt_sensors-master/mrpt_sensorlib/CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/adlir/catkin_ws/src/CMakeFiles/CMakeOutput.log".
Invoking "cmake" failed

what the matter is it ?

**Comment by jlblancoc** [comment]
Hi, 

Please, use mrpt-1.5 instead of the git `master` version of mrpt (1.9.9 as the time of writing) to build the ROS nodes, since there's still work to do to port them to the lastest version of mrpt. 

You can install it with: `sudo apt install ros-$ROSDISTRO-mrpt1`
