### ISSUE TITLE
cant launch node

### ISSUE THREAD

**Issue by Adlirrahaman** [mrpt-ros-pkg/mrpt_slam#52]
when i run the mrpt 2d i got the problem :

NODES
  /
    mrpt_ekf_slam_2d (mrpt_ekf_slam_2d/mrpt_ekf_slam_2d)
    rawlog_play_node (mrpt_rawlog/rawlog_play_node)
    rviz_nav (rviz/rviz)

auto-starting new master
process[master]: started with pid [24244]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 385b2052-078a-11e9-a036-90cdb63a51ff
process[rosout-1]: started with pid [24257]
started core service [/rosout]
**ERROR**: cannot launch node of type [mrpt_rawlog/rawlog_play_node]: can't locate node [rawlog_play_node] in package [mrpt_rawlog]
process[rviz_nav-3]: started with pid [24260]
**ERROR**: cannot launch node of type [mrpt_ekf_slam_2d/mrpt_ekf_slam_2d]: can't locate node [mrpt_ekf_slam_2d] in package [mrpt_ekf_slam_2d]

where should nodes must locate ? @jlblancoc

**Comment by Logrus** [comment]
I guess that one was resolved in another repo? If not, feel free to comment, I will reopen this issue.
