### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ROS-beginner** [mrpt-ros-pkg/mrpt_slam#59]
Hi everyone,

I'm new in Ros, and I'm trying to use mrpt_icp_slam_2d with my own simulation (on Gazebo). The problem is, when I'm running this node or Launching launch files, an example is running so I was wondering if I have to write a new launch file or just make some slight modification on existent ones ?
Thank your for your answers !

**Comment by jlblancoc** [comment]
Hi, 

Take [this files](https://github.com/mrpt-ros-pkg/mrpt_slam/blob/master/mrpt_icp_slam_2d/launch/icp_slam.launch) as a template, copy it somewhere on your own package and comment or remove line 16 (the include for the rosbag play). 

Also, adjust the names of all the parameters in lines 6 to 10 to match the frame names and topics used in your simulation. 

Cheers.
