### ISSUE TITLE
I could NOT install ros-melodic-mrpt-slam in Ubuntu 18.04 Melodic. 

### ISSUE THREAD

**Issue by leizhao3** [mrpt-ros-pkg/mrpt_slam#66]
Hi There,I'm having really difficulty on installing ros-melodic-mrpt-slam in Ubuntu 18.04 Melodic in my Odroid UX4. 

If I installed from apt-get, it could NOT find fetch one the address. Error below: 
code ran: `"sudo apt-get install ros-melodic-mrpt-slam"`
Error: 
> Err:1 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main armhf libudev-dev armhf 237-3ubuntu10.42
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/s/systemd/libudev-dev_237-3ubuntu10.42_armhf.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]

If I installed from the sources (this git: https://github.com/mrpt-ros-pkg/mrpt_slam), and it shows error below: 
code ran: `~/catkin_ws$ catkin_make `
Error: 
> CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
>   Could not find a package configuration file provided by "mrpt_bridge" with
>   any of the following names:
> 
>     mrpt_bridgeConfig.cmake
>     mrpt_bridge-config.cmake

To fix error above, I'm trying following:
code ran: `~/catkin_ws/src $ git clone https://github.com/mrpt-ros-pkg/mrpt_bridge/tree/ros1 #add mrpt_bridge package `
Error: 
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
>   Could not find a configuration file for package "mrpt-typemeta" that is
>   compatible with requested version "".
> 
>   The following configuration files were considered but not accepted:
> 
>     /usr/share/mrpt-typemeta/mrpt-typemeta-config.cmake, version: 2.1.3 (64bit)

I'm still NOT able to get the package installed, and I would really appreciate if anyone could provide a solution OR work around. Really appreciate your valuable input!

**Comment by ayrmoney** [comment]
I was able to install it via the steps below -

1. install mrpt from debian/ubuntu ppa from here, [[mrpt-install-ppa](https://docs.mrpt.org/reference/latest/download-mrpt.html#debian-ubuntu-ppa)](https://docs.mrpt.org/reference/latest/download-mrpt.html#debian-ubuntu-ppa)
2. make folder `mrpt-slam/src` in $HOME directory
3. git clone all PINNED pkgs from [[mrpt-ros-pkgs](https://github.com/mrpt-ros-pkg)](https://github.com/mrpt-ros-pkg) under src (if ros melodic, choose correct branch)
4. install pkg `ros-$ROS_DISTRO-marker-msgs` by sudo apt-get install
    
    ```bash
    sudo apt-get install ros-$ROS_DISTRO-marker-msgs
    ```
    
5. catkin build (being under mrpt-slam/)
