### ISSUE TITLE
Unable to compile mrpt_graphslam_2d

### ISSUE THREAD

**Issue by zhimouliang** [mrpt-ros-pkg/mrpt_slam#69]
Hi,
I am trying to run the whole slam process in mrpt_graph_slam_2d, however, this package depends on a specific version of mrpt since I found some APIs are different than latest mrpt, and I tried mrpt 2.3.0 and 2.5.0, which failed after I try a different combination of mrpt related package and some of the APIs doesn't match.
In order to make mrpt_graphslam_2d work, which version of mrpt should I build? Is there any guide I can follow to get the corresponding version for other mrpt related packages?
Appreciate the help!

**Comment by jlblancoc** [comment]
Hi @zhimouliang ! Have you tried the latest mrpt2 version from the ros distribution you are using? That is: 

```bash
sudo apt remove libmrpt*
sudo apt install ros-$ROS_DISTRO-mrpt2
```
and rebuild using catkin or colcon as usual?

The mrpt_slam package is in the wait for a complete reorganization and port to ros2, anyway... but we don't have a timeline for it yet. However, the current version should build and pass the tests, according to the ROS1 build farm Jenkins jobs [here](https://build.ros.org/job/Ndev__mrpt_slam__ubuntu_focal_amd64/)

**Comment by zhimouliang** [comment]
Hi @jlblancoc 
I tried your suggestion and make some tuning and finally make it compiled! Firstly I use apt install as much as possible(catkin_make sometimes fails even if they are in the same version with apt install). Secondly I checkout mrpt_msgs into 0.4.3 (ros1 is not compatible).
Thank you!

**Comment by zhimouliang** [comment]
Hi @jlblancoc 
However, while I try to run it an error pop up: "(MRPT:5786): Gtk-ERROR **: 11:21:32.975: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported".
Are there any way to fix it?
